# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2prod.ui'
#
# Created: Mon Sep 25 11:08:35 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 800)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.centralWidget.setFont(font)
        self.centralWidget.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.centralWidget.setAutoFillBackground(False)
        self.centralWidget.setStyleSheet("QWidget {background-color: black; color: white}\n"
"QPushButton{color: black; background-color: black}\n"
"QWidget::QLabel{font: 24 px; color: white; padding: 2 px; alignement: center}\n"
"QTabBar::tab {color:white; background: transparent; \n"
"border-top: 2px solid white; \n"
"border-left: 2px solid white; \n"
"border-right: 2px solid white; \n"
"text-align: center;\n"
"padding: 10px; font: 28px; width: 136px\n"
"}\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 0px solid black;\n"
"}\n"
"")
        self.centralWidget.setObjectName("centralWidget")
        self.tabMain = QtWidgets.QTabWidget(self.centralWidget)
        self.tabMain.setEnabled(True)
        self.tabMain.setGeometry(QtCore.QRect(0, 0, 480, 800))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabMain.setFont(font)
        self.tabMain.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.tabMain.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabMain.setIconSize(QtCore.QSize(64, 64))
        self.tabMain.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabMain.setMovable(False)
        self.tabMain.setObjectName("tabMain")
        self.tabUser = QtWidgets.QWidget()
        self.tabUser.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.tabUser.setObjectName("tabUser")
        self.btnL = QtWidgets.QPushButton(self.tabUser)
        self.btnL.setGeometry(QtCore.QRect(150, 70, 201, 211))
        self.btnL.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.btnL.setAutoFillBackground(False)
        self.btnL.setStyleSheet("")
        self.btnL.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/left-arrow-button (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/images/left-arrow-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnL.setIcon(icon)
        self.btnL.setIconSize(QtCore.QSize(200, 200))
        self.btnL.setDefault(False)
        self.btnL.setFlat(True)
        self.btnL.setObjectName("btnL")
        self.btnR = QtWidgets.QPushButton(self.tabUser)
        self.btnR.setGeometry(QtCore.QRect(150, 360, 201, 201))
        self.btnR.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.btnR.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/right-arrow-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/images/right-arrow-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnR.setIcon(icon1)
        self.btnR.setIconSize(QtCore.QSize(200, 200))
        self.btnR.setFlat(True)
        self.btnR.setObjectName("btnR")
        self.btnVideo = QtWidgets.QPushButton(self.tabUser)
        self.btnVideo.setGeometry(QtCore.QRect(10, 630, 81, 81))
        self.btnVideo.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.btnVideo.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/video.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(":/images/video.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(":/images/video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/images/video.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.btnVideo.setIcon(icon2)
        self.btnVideo.setIconSize(QtCore.QSize(75, 75))
        self.btnVideo.setFlat(True)
        self.btnVideo.setObjectName("btnVideo")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/two-way-arrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabMain.addTab(self.tabUser, icon3, "")
        self.tabLight = QtWidgets.QWidget()
        self.tabLight.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.tabLight.setObjectName("tabLight")
        self.btnL1 = QtWidgets.QPushButton(self.tabLight)
        self.btnL1.setGeometry(QtCore.QRect(230, 90, 200, 200))
        self.btnL1.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.btnL1.setStyleSheet("selection-background-color: rgb(0, 0, 0);\n"
"selection-color: rgb(0, 0, 0);")
        self.btnL1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/idea (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnL1.setIcon(icon4)
        self.btnL1.setIconSize(QtCore.QSize(200, 200))
        self.btnL1.setFlat(True)
        self.btnL1.setObjectName("btnL1")
        self.btnL2 = QtWidgets.QPushButton(self.tabLight)
        self.btnL2.setGeometry(QtCore.QRect(230, 470, 200, 200))
        self.btnL2.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.btnL2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/BOUTON - SALLE DE BAIN (JOUR).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon5.addPixmap(QtGui.QPixmap(":/images/idea (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnL2.setIcon(icon5)
        self.btnL2.setIconSize(QtCore.QSize(200, 200))
        self.btnL2.setFlat(True)
        self.btnL2.setObjectName("btnL2")
        self.labelwash = QtWidgets.QLabel(self.tabLight)
        self.labelwash.setGeometry(QtCore.QRect(240, 410, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelwash.setFont(font)
        self.labelwash.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.labelwash.setObjectName("labelwash")
        self.labelkitc = QtWidgets.QLabel(self.tabLight)
        self.labelkitc.setGeometry(QtCore.QRect(280, 30, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelkitc.setFont(font)
        self.labelkitc.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.labelkitc.setObjectName("labelkitc")
        self.btnL3 = QtWidgets.QPushButton(self.tabLight)
        self.btnL3.setGeometry(QtCore.QRect(40, 260, 200, 200))
        self.btnL3.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.btnL3.setText("")
        self.btnL3.setIcon(icon4)
        self.btnL3.setIconSize(QtCore.QSize(200, 200))
        self.btnL3.setFlat(True)
        self.btnL3.setObjectName("btnL3")
        self.labelroof = QtWidgets.QLabel(self.tabLight)
        self.labelroof.setGeometry(QtCore.QRect(60, 200, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelroof.setFont(font)
        self.labelroof.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.labelroof.setObjectName("labelroof")
        self.tabMain.addTab(self.tabLight, icon4, "")
        self.tabAdmin = QtWidgets.QWidget()
        self.tabAdmin.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.tabAdmin.setStyleSheet("QPushButton { background-color: white }")
        self.tabAdmin.setObjectName("tabAdmin")
        self.lcdWaterCons = QtWidgets.QLCDNumber(self.tabAdmin)
        self.lcdWaterCons.setGeometry(QtCore.QRect(20, 60, 141, 81))
        self.lcdWaterCons.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lcdWaterCons.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdWaterCons.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdWaterCons.setDigitCount(5)
        self.lcdWaterCons.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdWaterCons.setProperty("value", 0.0)
        self.lcdWaterCons.setObjectName("lcdWaterCons")
        self.btnErr1 = QtWidgets.QPushButton(self.tabAdmin)
        self.btnErr1.setEnabled(True)
        self.btnErr1.setGeometry(QtCore.QRect(70, 240, 81, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnErr1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.btnErr1.setFont(font)
        self.btnErr1.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.btnErr1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/warning_black.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap(":/images/warning_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/images/warning_black.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/images/warning_black.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/images/warning_black.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap(":/images/warning_black.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap(":/images/warning_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap(":/images/warning_black.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.btnErr1.setIcon(icon6)
        self.btnErr1.setIconSize(QtCore.QSize(75, 75))
        self.btnErr1.setFlat(True)
        self.btnErr1.setObjectName("btnErr1")
        self.btnErr2 = QtWidgets.QPushButton(self.tabAdmin)
        self.btnErr2.setEnabled(True)
        self.btnErr2.setGeometry(QtCore.QRect(70, 340, 81, 71))
        self.btnErr2.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.btnErr2.setText("")
        self.btnErr2.setIcon(icon6)
        self.btnErr2.setIconSize(QtCore.QSize(75, 75))
        self.btnErr2.setFlat(True)
        self.btnErr2.setObjectName("btnErr2")
        self.Err1lbl = QtWidgets.QLabel(self.tabAdmin)
        self.Err1lbl.setEnabled(False)
        self.Err1lbl.setGeometry(QtCore.QRect(170, 250, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Err1lbl.setFont(font)
        self.Err1lbl.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.Err1lbl.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.Err1lbl.setAcceptDrops(False)
        self.Err1lbl.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Err1lbl.setText("")
        self.Err1lbl.setWordWrap(False)
        self.Err1lbl.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Err1lbl.setObjectName("Err1lbl")
        self.Err2lbl = QtWidgets.QLabel(self.tabAdmin)
        self.Err2lbl.setEnabled(False)
        self.Err2lbl.setGeometry(QtCore.QRect(170, 350, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Err2lbl.setFont(font)
        self.Err2lbl.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.Err2lbl.setText("")
        self.Err2lbl.setObjectName("Err2lbl")
        self.btnWtrCntrRst = QtWidgets.QPushButton(self.tabAdmin)
        self.btnWtrCntrRst.setGeometry(QtCore.QRect(380, 10, 91, 41))
        self.btnWtrCntrRst.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.btnWtrCntrRst.setObjectName("btnWtrCntrRst")
        self.labelcons = QtWidgets.QLabel(self.tabAdmin)
        self.labelcons.setEnabled(True)
        self.labelcons.setGeometry(QtCore.QRect(20, 9, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labelcons.setFont(font)
        self.labelcons.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.labelcons.setObjectName("labelcons")
        self.lblLastRst = QtWidgets.QLabel(self.tabAdmin)
        self.lblLastRst.setEnabled(True)
        self.lblLastRst.setGeometry(QtCore.QRect(20, 160, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblLastRst.setFont(font)
        self.lblLastRst.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblLastRst.setObjectName("lblLastRst")
        self.Err3lbl = QtWidgets.QLabel(self.tabAdmin)
        self.Err3lbl.setEnabled(False)
        self.Err3lbl.setGeometry(QtCore.QRect(170, 450, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Err3lbl.setFont(font)
        self.Err3lbl.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.Err3lbl.setText("")
        self.Err3lbl.setObjectName("Err3lbl")
        self.btnErr3 = QtWidgets.QPushButton(self.tabAdmin)
        self.btnErr3.setEnabled(True)
        self.btnErr3.setGeometry(QtCore.QRect(70, 440, 81, 71))
        self.btnErr3.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.btnErr3.setText("")
        self.btnErr3.setIcon(icon6)
        self.btnErr3.setIconSize(QtCore.QSize(75, 75))
        self.btnErr3.setFlat(True)
        self.btnErr3.setObjectName("btnErr3")
        self.btnStopWater = QtWidgets.QPushButton(self.tabAdmin)
        self.btnStopWater.setEnabled(True)
        self.btnStopWater.setGeometry(QtCore.QRect(0, 612, 111, 100))
        self.btnStopWater.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.btnStopWater.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/block-faucet.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon7.addPixmap(QtGui.QPixmap(":/images/block-faucet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/images/block-faucet.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/images/block-faucet.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/images/block-faucet.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon7.addPixmap(QtGui.QPixmap(":/images/block-faucet.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon7.addPixmap(QtGui.QPixmap(":/images/block-faucet.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon7.addPixmap(QtGui.QPixmap(":/images/block-faucet.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.btnStopWater.setIcon(icon7)
        self.btnStopWater.setIconSize(QtCore.QSize(100, 100))
        self.btnStopWater.setFlat(True)
        self.btnStopWater.setObjectName("btnStopWater")
        self.contactlbl = QtWidgets.QLabel(self.tabAdmin)
        self.contactlbl.setEnabled(False)
        self.contactlbl.setGeometry(QtCore.QRect(110, 640, 251, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.contactlbl.setFont(font)
        self.contactlbl.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.contactlbl.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"qproperty-alignment: \'AlignVCenter | AlignCenter\';\n"
"qproperty-wordWrap: true;")
        self.contactlbl.setObjectName("contactlbl")
        self.btnWtrCntrUnit = QtWidgets.QPushButton(self.tabAdmin)
        self.btnWtrCntrUnit.setGeometry(QtCore.QRect(180, 80, 271, 51))
        self.btnWtrCntrUnit.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.btnWtrCntrUnit.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 24pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"selection-color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"text-color: (255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"Text-align:left")
        self.btnWtrCntrUnit.setFlat(False)
        self.btnWtrCntrUnit.setObjectName("btnWtrCntrUnit")
        self.btnLanguage = QtWidgets.QPushButton(self.tabAdmin)
        self.btnLanguage.setGeometry(QtCore.QRect(360, 650, 121, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.btnLanguage.setPalette(palette)
        self.btnLanguage.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.btnLanguage.setStyleSheet("selection-background-color: rgb(0, 0, 0);\n"
"font: 32pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.btnLanguage.setText("Fr")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/speech-bubble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/images/speech-bubble.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.btnLanguage.setIcon(icon8)
        self.btnLanguage.setIconSize(QtCore.QSize(50, 50))
        self.btnLanguage.setAutoDefault(False)
        self.btnLanguage.setFlat(True)
        self.btnLanguage.setObjectName("btnLanguage")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/wrench.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabMain.addTab(self.tabAdmin, icon9, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelwash.setText(_translate("MainWindow", "Salle de bain"))
        self.labelkitc.setText(_translate("MainWindow", "Cuisine"))
        self.labelroof.setText(_translate("MainWindow", "Plafonnier"))
        self.btnWtrCntrRst.setText(_translate("MainWindow", "RESET"))
        self.labelcons.setText(_translate("MainWindow", "Consomation d\'eau"))
        self.lblLastRst.setText(_translate("MainWindow", "Depuis le"))
        self.contactlbl.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Contact info lorem ipsum lorem ipsumlorem ipsumlorem ipsumlorem</span></p></body></html>"))
        self.btnWtrCntrUnit.setText(_translate("MainWindow", "Gallons"))

import ressources_rc
